trigger:
  branches:
    include:
<<<<<<< HEAD
      - main
=======
      - main  # Trigger on changes to the main branch
>>>>>>> 06fd6d38f30d9dbb0668699b617a052ad33b95d0

stages:
  - stage: Build
    jobs:
      - job: BuildAndDeploy
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "16.x"  # Use Node.js version 16.x
            displayName: "Install Node.js"

          - script: |
              echo "Changing directory to frontend..."
              cd wallet-watch-frontend
              echo "Installing packages for frontend..."
              npm install
              ng build --configuration=production --output-path=../wallet-watch-backend/public
            displayName: "Build Frontend"

          - script: |
              echo "Creating directory for backend public folder..."
              mkdir -p wallet-watch-backend/public
              echo "Copying frontend build to backend public folder..."
              cp -r wallet-watch-frontend/dist/* wallet-watch-backend/public/
            displayName: "Copy Frontend Build to Backend"

          - script: |
              echo "Changing directory to backend..."
              cd wallet-watch-backend
              echo "Installing backend dependencies..."
              npm install
            displayName: "Install Backend Dependencies"

          - task: AzureWebApp@1
            inputs:
              azureSubscription: "WalletWatch"  # Ensure this is the correct Azure service connection
              appName: "WalletWatch"  # Ensure this is the correct App Service name in Azure
              package: "walletwatch"  # Make sure this points to the correct directory containing the deployable code
            displayName: "Deploy to Azure Web App"
