trigger:
  branches:
    include:
      - main

stages:
  - stage: Build
    jobs:
      - job: BuildAndDeploy
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "17.x"  # Use Node.js version 16.x
            displayName: "Install Node.js"

          - script: |
              echo "Changing directory to backend..."
              echo "Installing backend dependencies..."
              npm install --legacy-peer-deps
            displayName: "Install Backend Dependencies"

          - task: AzureWebApp@1
            inputs:
              azureSubscription: "4e0c0a5d-ae53-475e-bd8e-7fd99e6aa32e"  # Ensure this is the correct Azure service connection
              appName: "WalletWatch"  # Ensure this is the correct App Service name in Azure
              package: "walletwatch"  # Make sure this points to the correct directory containing the deployable code
            displayName: "Deploy to Azure Web App"
