name: Build and deploy Node.js app to Azure Web App - WalletWatch

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Node.js version
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Install and build frontend
      - name: Install and build frontend
        working-directory: wallet-watch-frontend
        run: |
          npm install
          npm run build

      # Move frontend build to backend
      - name: Move frontend build to backend
        run: |
          cp -r wallet-watch-frontend/public wallet-watch-backend/public

      # Install and build backend
      - name: Install and build backend
        working-directory: wallet-watch-backend
        run: |
          npm install
          npm run build --if-present

      # Upload backend (which now includes frontend build) for deployment
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: walletwatch-app
          path: wallet-watch-backend

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build
        uses: actions/download-artifact@v4
        with:
          name: walletwatch-app

      # Login to Azure
     # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ 5e56d5fb-4137-4475-ad06-71df489c6680 }}
          tenant-id: ${{ bc10e052-b01c-4849-9967-ee7ec74fc9d8 }}
          client-secret: ${{ XOP8Q~LrnQltbBuYEdwxUjyGwjD_CXKtruuz1byN }}

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'WalletWatch'
          package: wallet-watch-backend
